### PR TITLE
ShortDesc name field is optional

### PR DESCRIPTION
**Pull request by lionelvillard**

### CODE REVIEW

**Comment by gbdrt** [comment]
LGTM.
But what is the usecase where you don't need to provide a name?

**Comment by lionelvillard** [comment]
At least for `packages.update` the name argument is at the top-level. The one is `Package` is ignored.

**Comment by jthomas** [comment]
Can you re-base this PR to resolve the build issue now I've fixed the trigger failure?

**Comment by csantanapr** [comment]
rebased.

**Pull request merged**
