### PR TITLE
chore: Ignore .idea directory from git

### PR DESCRIPTION
**Pull request by ert78gb**
Why do you ignore package.lock.json ?

### CODE REVIEW

**Comment by jthomas** [comment]
@ert78gb I understand this is a tiny change but I don't think it's desirable to start adding lots of editor-specific files to the main `.gitignore`. Developers are free to add these in for their own configuration locally.

I'm not sure why `package.lock.json` is in there.

**Comment by ert78gb** [comment]
ok I accept it.

**Comment by ert78gb** [comment]
could I add .nvmrc file to the repo or is it same user settings?

**Comment by jthomas** [comment]
Same as above I'm afraid.

**Pull request closed without merging**
