### PR TITLE
support adding your own cert and key

### PR DESCRIPTION
**Pull request by shazron**
Adds support for setting the cert and key like the Go client.
Option is added in the Client constructor.

### CODE REVIEW

**Comment by shazron** [comment]
Similarly for #151...
@jthomas looks like the PR failed due to "./tools/travis/scancode.sh issues, not related to my code? Do I need to fix those in another PR?

**Comment by shazron** [comment]
Filed #153 for scancode issues (not entirely solved, because of a scancode limitation...)

**Comment by jthomas** [comment]
@csantanapr this travis build also needs restarting.... cheers!

@shazron thanks for this - I'll work on getting this into an official release shortly.

**Comment by csantanapr** [comment]
Anyone can restart Travis just close and then reopen the PR

**Pull request merged**
