### PR TITLE
support setting the apiversion

### PR DESCRIPTION
**Pull request by shazron**
Adds support for setting the `apiversion` like the Go client.
Option is added in the Client constructor.

### CODE REVIEW

**Comment by shazron** [comment]
@jthomas looks like the PR failed due to `"./tools/travis/scancode.sh` issues, not related to my code? Do I need to fix those in another PR?

**Comment by shazron** [comment]
Filed #153 for scancode issues (not entirely solved, because of a scancode limitation...)

**Comment by jthomas** [comment]
Thanks for this @shazron - you even updated the docs and added tests without asking ❤️

**Comment by jthomas** [comment]
@csantanapr do you have travis access to restart the travis build for this pr?

**Comment by csantanapr** [comment]
Anyone can restart Travis just close the PR and re open

**Comment by jthomas** [comment]
@shazron can you update this PR will the latest changes to fix the merge conflict?

**Pull request merged**
