### PR TITLE
v3.12.0 NPM version bump

### PR DESCRIPTION
**Pull request by jthomas**
## notes for release page

- Retain namespace get support even though platform is deprecating this endpoint. (#94, #95)

### CODE REVIEW

**Comment by jthomas** [comment]
@rabbah once this has been reviewed and merged  @csantanapr will need to create tag for NPM auto-publish to be triggered.

**Comment by jthomas** [comment]
@csantanapr What do we need to do to trigger off the release auto-publish to NPM? Do you have to create the release on GH (release notes above)? 

cc @rabbah

**Comment by csantanapr** [comment]
@jthomas tagged as 3.12.0

**Comment by rabbah** [comment]
Need to bump version we include in action runtimes?

**Pull request merged**
