### PR TITLE
feat: Support version when create / update action

### PR DESCRIPTION
**Pull request by ert78gb**
The [REST API](https://console.bluemix.net/apidocs/98-ibm-bluemix-openwhisk?=undefined&language=node&env_id=ibm:yp:eu-gb#create-or-update-an-action) support version number, when create or update an action. The parameter is optional and if it is empty the system increment the patch version number.

When action invoke the system store the version number in the log. Very useful to know what version of the action have invoked when investigating a bug.

### CODE REVIEW

**Comment by jthomas** [comment]
I didn't know the version could be set, that's interesting @ert78gb. 

Thanks for adding tests along with the code. Can you please update the README to document this new parameter?

**Comment by ert78gb** [comment]
I added and set the code snippet language for syntax highlight

**Comment by jthomas** [comment]
Thanks, this LGTM. 

@csantanapr review & merge? So I can release on NPM.

**Comment by ert78gb** [comment]
I resolved the conflict pls merge or close my PR-s.

**Pull request merged**
